name: Build

on:
  schedule:
    - cron: '0 7 * * *'
  workflow_dispatch:
    
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      # - name: NASM
      #   uses: ilammy/setup-nasm@v1
      - name: Checkout
        uses: nschloe/action-cached-lfs-checkout@v1
      - name: Get current date
        id: date
        run: echo "::set-output name=date::$(date +'%Y-%m-%d')"
      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 16.17.1
      - name: Install dependencies
        run: npm install
        working-directory: ${{ github.workspace }}/project
      - name: Build project
        run: npm run build:release
        working-directory: ${{ github.workspace }}/project
      - name: Rename file
        run: mv Aki.Server.exe Aki.Server
        working-directory: ${{ github.workspace }}/project/build
      - name: Archive Release
        uses: thedoctor0/zip-release@0.7.1
        with:
          type: 'zip'
          filename: 'Server-${{ steps.date.outputs.date }}.zip'
          directory: 'project/build/'
          exclusions: '*.git* /*node_modules/* .editorconfig'
      - name: Upload files to release
        uses: softprops/action-gh-release@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          files: project/build/Server-${{ steps.date.outputs.date }}.zip
          tag_name: ${{ steps.date.outputs.date }}
          name: 基于x64-Linux编译的服务端
      - name: Remove old Releases
        uses: dev-drprasad/delete-older-releases@v0.1.0
        with:
          keep_latest: 3
          delete_tags: true
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
